import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { _electron as electron } from "playwright-core";

const root = fileURLToPath(new URL("../../", import.meta.url));
const executablePath = path.join(root, "node_modules/electron/dist/electron.exe");
const output = path.join(os.tmpdir(), "booth-chat-desktop-previews");

test("desktop chat moves one live view between native windows without losing its state", { timeout: 180_000 }, async (t) => {
  console.log("Native check: launching isolated Electron");
  const app = await electron.launch({ executablePath, timeout: 30_000, args: [path.join(root, "tests/ui/chatNativeMain.cjs"), ...(process.env.BOOTH_TEST_BUILT === "1" ? ["--booth-chat-built"] : [])] });
  t.after(async () => {
    const killTimer = setTimeout(() => app.process().kill(), 8000);
    try { await app.close(); } finally { clearTimeout(killTimer); }
  });
  const main = await app.firstWindow({ timeout: 30_000 });
  console.log("Native check: fixture loaded");
  main.setDefaultTimeout(20_000);
  const errors = [];
  main.on("pageerror", (error) => errors.push(error.message));
  await main.getByRole("button", { name: "Team Chat", exact: true }).click();
  const input = main.getByRole("textbox", { name: "Message Test Creators", exact: true });
  await input.waitFor();
  await main.getByRole("button", { name: "Send message", exact: true }).waitFor();
  await input.fill("draft stays in this room");
  await input.selectText();
  await main.getByRole("button", { name: "Bold", exact: true }).click();
  assert.equal(await input.inputValue(), "**draft stays in this room**");
  await main.getByRole("button", { name: "Preview", exact: true }).click();
  assert.equal(await main.locator('.chat-composer-preview strong').innerText(), "draft stays in this room");
  await main.getByRole("button", { name: "Write", exact: true }).click();
  console.log("Native check: composer formatting passed");
  await main.evaluate(() => {
    window.__chatFixture.nextFiles = { ok: true, files: [{ id: "pending-test", name: "layout-plan.txt", kind: "file", size: 600, mime: "text/plain" }] };
    window.__chatFixture.messages["room-a"].push({
      id: "markdown-test", authorId: "test-avery", authorName: "Avery", authorRole: "manager", createdAt: new Date().toISOString(), attachments: [],
      body: "# Update\n\n**Ready**, @Cadyn.\n\n- [x] Layout\n- [ ] Rehearsal\n\n| Item | Status |\n| --- | --- |\n| Booth | OK |\n\n```js\nconst count = 2;\n```\n\n![Plan](https://images.fixture.invalid/plan.png)\n\n<script>window.badMarkdown=true</script>"
    });
  });
  await main.getByRole("button", { name: "Attach local files", exact: true }).click();
  await main.getByRole("button", { name: "Refresh messages", exact: true }).click();
  await main.locator('[data-message-id="markdown-test"] .hljs-keyword').waitFor();
  assert.equal(await main.locator('[data-message-id="markdown-test"] table').count(), 1);
  assert.equal(await main.locator('[data-message-id="markdown-test"] input[disabled]').count(), 2);
  assert.equal(await main.locator('[data-message-id="markdown-test"] img').count(), 0);
  assert.equal(await main.evaluate(() => Boolean(window.badMarkdown)), false);
  await fs.mkdir(output, { recursive: true });
  await main.screenshot({ path: path.join(output, "chat-docked.png") });
  await main.evaluate(() => {
    window.__originalComposer = document.querySelector(".chat-composer-input");
    window.__originalPortal = document.querySelector(".chat-portal-root");
    window.__chatFeedScroll = document.querySelector(".message-feed");
    window.__chatFeedScroll.scrollTop = 250;
    const original = window.open.bind(window);
    window.open = (...args) => { const popup = original(...args); if (popup) window.__nativeChatPopup = popup; return popup; };
  });
  const opened = app.waitForEvent("window");
  console.log("Native check: opening first popup");
  await main.getByRole("button", { name: "Pop out chat", exact: true }).click();
  const popup = await opened;
  popup.setDefaultTimeout(20_000);
  popup.on("pageerror", (error) => errors.push(error.message));
  await popup.getByRole("button", { name: "Dock chat", exact: true }).waitFor();
  console.log("Native check: first popup ready");
  assert.equal(await main.locator(".chat-workspace").count(), 0);
  assert.equal(await popup.locator(".chat-workspace").count(), 1);
  assert.equal(await popup.getByRole("textbox", { name: "Message Test Creators" }).inputValue(), "**draft stays in this room**");
  await popup.getByRole("button", { name: "Remove layout-plan.txt" }).waitFor();
  assert.equal(await main.evaluate(() => window.__originalComposer === window.__nativeChatPopup.document.querySelector(".chat-composer-input")), true);
  assert.equal(await main.evaluate(() => window.__originalPortal === window.__nativeChatPopup.document.querySelector(".chat-portal-root")), true);
  assert.equal(await popup.locator(".message-feed").evaluate((node) => Math.abs(node.scrollTop - 250) < 5), true);
  assert.equal(await popup.getByRole("button", { name: "Pop out chat", exact: true }).count(), 0);
  await main.getByRole("button", { name: "Focus chat window", exact: true }).click();
  await main.evaluate(() => { for (let index = 0; index < 5; index += 1) window.open("about:blank", "booth-manager-chat", "popup"); });
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 2);
  const popInput = popup.getByRole("textbox", { name: "Message Test Creators" });
  await popInput.fill("native keyboard");
  await popInput.press("End");
  await popInput.pressSequentially(" input");
  await popInput.selectText();
  await popInput.press("Control+b");
  assert.equal(await popInput.inputValue(), "**native keyboard input**");
  await popInput.press("Control+z");
  assert.equal(await popInput.inputValue(), "native keyboard input");
  await popInput.dispatchEvent("compositionstart", { data: "test" });
  await popInput.dispatchEvent("keydown", { key: "Enter", code: "Enter", keyCode: 229, isComposing: true });
  await popInput.dispatchEvent("compositionend", { data: "test" });
  assert.equal(await main.evaluate(() => window.__chatFixture.sent.length), 0);
  await popup.getByRole("button", { name: "Lock room", exact: true }).click();
  await popup.getByRole("dialog", { name: "Lock this room?", exact: true }).waitFor();
  assert.equal(await main.getByRole("dialog").count(), 0);
  assert.equal(await popup.evaluate(() => document.activeElement.textContent), "Cancel");
  await popup.keyboard.press("Shift+Tab");
  assert.equal(await popup.evaluate(() => document.activeElement.textContent), "Lock room");
  await popup.keyboard.press("Escape");
  assert.equal(await popup.getByRole("dialog").count(), 0);
  await popInput.fill("**Edited in popout**\n\n> A quote");
  await popup.getByRole("button", { name: "Preview", exact: true }).click();
  assert.equal(await popup.locator(".chat-composer-preview blockquote").count(), 1);
  await popup.getByRole("button", { name: "Write", exact: true }).click();
  await popup.getByRole("button", { name: "Chat settings", exact: true }).click();
  await popup.getByRole("button", { name: "Close chat panel", exact: true }).click();
  await main.getByRole("button", { name: "Dashboard", exact: true }).click();
  await popInput.fill("draft while the main window is elsewhere");
  await popup.screenshot({ path: path.join(output, "chat-popout.png") });
  const heldScroll = await popup.locator(".message-feed").evaluate((node) => { node.scrollTop = 420; return node.scrollTop; });
  assert.ok(heldScroll > 0);
  await popup.getByRole("button", { name: "Dock chat", exact: true }).click();
  console.log("Native check: explicit dock finished");
  await main.getByRole("textbox", { name: "Message Test Creators", exact: true }).waitFor();
  assert.equal(await input.inputValue(), "draft while the main window is elsewhere");
  assert.equal(await main.evaluate(() => window.__originalComposer === document.querySelector(".chat-composer-input")), true);
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  assert.ok(await main.locator(".message-feed").evaluate((node, top) => Math.abs(node.scrollTop - top) < 5, heldScroll), "Docking from another page preserves reading position");
  await main.getByRole("button", { name: "Remove layout-plan.txt" }).waitFor();
  const secondOpened = app.waitForEvent("window");
  await main.getByRole("button", { name: "Pop out chat", exact: true }).click();
  const second = await secondOpened;
  await second.getByRole("button", { name: "Dock chat", exact: true }).waitFor();
  await app.evaluate(() => global.__chatTest.manager.getWindow().setSize(980, 700));
  await second.waitForFunction(() => innerWidth < 1000);
  await second.screenshot({ path: path.join(output, "chat-popout-minimum.png") });
  assert.equal(await second.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.equal(await second.getByRole("textbox", { name: "Message Test Creators" }).isVisible(), true);
  await second.getByRole("button", { name: "Chat settings", exact: true }).click();
  await second.screenshot({ path: path.join(output, "chat-popout-settings.png") });
  await second.getByRole("button", { name: "Close chat panel", exact: true }).click();
  await app.evaluate(() => global.__chatTest.main.hide());
  await second.getByRole("textbox", { name: "Message Test Creators" }).fill("restored after the native close button");
  await app.evaluate(() => global.__chatTest.manager.getWindow().close());
  console.log("Native check: native close requested");
  await input.waitFor();
  assert.equal(await input.inputValue(), "restored after the native close button");
  assert.equal(await app.evaluate(() => global.__chatTest.main.isVisible()), true);
  assert.equal(await app.evaluate(() => global.__chatTest.manager.getState().detached), false);
  const thirdOpened = app.waitForEvent("window");
  await main.getByRole("button", { name: "Pop out chat", exact: true }).click();
  const third = await thirdOpened;
  await third.getByRole("textbox", { name: "Message Test Creators" }).fill("one delayed send across docking");
  await main.evaluate(() => { window.__chatFixture.holdSend = true; });
  await third.getByRole("button", { name: "Send message", exact: true }).click();
  await main.waitForFunction(() => window.__chatFixture.deferred.some((job) => job.kind === "send"));
  await app.evaluate(() => global.__chatTest.manager.getWindow().close());
  await main.evaluate(() => { window.__chatFixture.deferred.find((job) => job.kind === "send").resolve(); });
  await main.waitForFunction(() => document.querySelector(".chat-composer-input").value === "");
  assert.equal(await main.evaluate(() => window.__chatFixture.sent.filter((entry) => entry.message.body === "one delayed send across docking").length), 1);
  console.log("Native check: delayed send survived docking");
  assert.equal(await main.getByRole("button", { name: "Remove layout-plan.txt" }).count(), 0);
  await app.evaluate(() => global.__chatTest.main.setSize(1120, 700));
  await main.screenshot({ path: path.join(output, "chat-desktop-minimum.png") });
  assert.equal(await main.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.equal(await input.isVisible(), true);
  await main.getByRole("button", { name: "Open Alley Lounge", exact: true }).click();
  assert.equal(await main.getByRole("button", { name: "Attach local files", exact: true }).count(), 0);
  await main.getByRole("textbox", { name: "Message Alley Lounge" }).fill("![No inline loading](https://images.fixture.invalid/hidden.png)");
  await main.getByRole("button", { name: "Preview", exact: true }).click();
  assert.equal(await main.locator(".chat-composer-preview img").count(), 0);
  assert.equal(await main.locator(".chat-composer-preview").getByRole("button", { name: "Load image", exact: true }).count(), 0);
  await main.getByRole("button", { name: "Write", exact: true }).click();
  const lastOpened = app.waitForEvent("window");
  await main.getByRole("button", { name: "Pop out chat", exact: true }).click();
  const last = await lastOpened;
  await last.getByRole("button", { name: "Dock chat", exact: true }).waitFor();
  await main.getByRole("button", { name: "Settings", exact: true }).click();
  await main.getByRole("button", { name: /Sign out/i }).click();
  await main.waitForFunction(() => !window.__nativeChatPopup || window.__nativeChatPopup.closed);
  assert.equal(await app.evaluate(() => global.__chatTest.manager.getState().detached), false);
  assert.deepEqual(errors, []);
  assert.deepEqual(await main.evaluate(() => window.__chatFixture.errors), []);
  assert.deepEqual(await app.evaluate(() => global.__chatTest.blockedRequests.filter((url) => !url.includes("fonts.googleapis.com") && !url.includes("fonts.gstatic.com"))), []);
  console.log(`Desktop screenshots: ${output}`);
});